//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperStore_WebSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CTPHIEUNHAP
    {
        public string MAPHNHAP { get; set; }
        public string MASP { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập số lượng.")]
        public Nullable<int> SOLUONG { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập giá nhâpj.")]
        public Nullable<double> GIANHAP { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
    
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
