//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperStore_WebSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.CompilerServices;

    public partial class KHUYENMAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHUYENMAI()
        {
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
        [Required(ErrorMessage = "Vui lòng nhập mã khuyến mãi.")]
        public string MAKM { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn ngày bắt đầu.")]
        [DateTimeConstant(ErrorMessage = "Ngày bắt đầu không được nhỏ hơn hôm nay.")]
        public Nullable<DateTime> NGAYBD { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn ngày kết thúc.")]
        [DateTimeConstant(ErrorMessage = "Ngày kết thúc không được nhỏ hơn hôm nay.")]
        public Nullable<System.DateTime> NGAYKT { get; set; }
        [Range(typeof(double), "0", "9999999.99", ErrorMessage = "Giá giảm phải là một số dương.")]
        public Nullable<double> GIAGIAM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
        public class DateTimeConstantAttribute : ValidationAttribute
        {
            public override bool IsValid(object value)
            {
                if (value is DateTime dateTimeValue)
                {
                    return dateTimeValue.Date >= DateTime.Now.Date;
                }
                return true;
            }
        }
    }
}
