//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperStore_WebSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.HOADONs = new HashSet<HOADON>();
            this.PHIEUNHAPs = new HashSet<PHIEUNHAP>();
        }

        
        public string MANV { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên nhân viên.")]
        public string TENNV { get; set; }
       
        public Nullable<System.DateTime> NGAYSINH { get; set; }
      
        public string GIOITINH { get; set; }        
        public string SDT { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập địa chỉ nhân viên.")]
        public string DIACHI { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập chức vụ nhân viên.")]
        public string CHUCVU { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập email nhân viên.")]
        [EmailAddress(ErrorMessage = "Địa chỉ email không hợp lệ.")]
        public string EMAIL { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập mật khẩu.")]
        public string PASSWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUNHAP> PHIEUNHAPs { get; set; }
    }
}
