//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperStore_WebSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTHDs = new HashSet<CTHD>();
            this.CTPHIEUNHAPs = new HashSet<CTPHIEUNHAP>();
        }       
        public string MASP { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên sản phẩm.")]
        public string TENSP { get; set; }       
        public string MALOAI { get; set; }
        public string MANCC { get; set; }
        public string MAKM { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập giá bán.")]
        [Range(typeof(double), "0", "9999999.99", ErrorMessage = "Giá nhập phải là một số dương.")]
        public Nullable<double> GIABAN { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }    
        public string GHICHU { get; set; }       
        public string HINHANH { get; set; }
        public string HINHLIENQUAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUNHAP> CTPHIEUNHAPs { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual LOAI LOAI { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
